### ISSUE TITLE
Rename CONFIG env variable to _CONFIGTOOLS_CONFIG

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/configtools#11]
`CONFIG` is too generic. This will involve a simple change in `configtools` but it will require more extensive changes in its users (`pbench/agent` and `pbench/server`).

Is `_CONFIGTOOLS_CONFIG` sufficiently difficult to trip over?

**Comment by portante** [comment]
Seems fine to me.

**Comment by riya-17** [comment]
Hey @portante @ndokos I would like to work on this issue

**Comment by portante** [comment]
@riya-17, can we consider #19 first?

**Comment by riya-17** [comment]
Sure @portante I would like to take the issue. Please assign me that issue
